{
 "title": "Model Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "continuous",
    "query": {
     "query": "metrics(feature_([0-9].*)_value_bucket)"
    }
   },
   {
    "name": "discrete",
    "query": {
     "query": "metrics(feature_([0-9].*)_value_total)"
    }
   },
   {
    "name": "interval",
    "query": "2m, 5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "duration", "query": "2m" }
  ]
 },
 "panels": [
  {
   "title": "Wine Predictions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(inference_value_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "K-S Test (30m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum(inference_value_baseline_bucket) by (le) / ignoring(le) group_left max(sum(inference_value_baseline_bucket) by (le)) -\nsum(increase(inference_value_bucket[30m])) by (le) / ignoring(le) group_left max(sum(increase(inference_value_bucket[30m])) by (le))\n))",
     "legendFormat": "yhat={{le}}"
    }
   ]
  },
  {
   "title": "Baseline distribution over test set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(inference_value_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "continuous" },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  { "title": "$continuous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Baseline distribution over training set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum([[continuous]]_baseline_bucket) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Feature value distribution over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase([[continuous]]_bucket[$duration])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "K-S Test over $duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, abs(\nsum([[continuous]]_baseline_bucket) by (le) / ignoring(le) group_left max(sum([[continuous]]_baseline_bucket) by (le)) -\nsum(increase([[continuous]]_bucket[$duration])) by (le) / ignoring(le) group_left max(sum(increase([[continuous]]_bucket[$duration])) by (le))\n))",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}